# TCL File Generated by Component Editor 15.1
# Mon Mar 26 10:53:58 GMT+03:00 2018
# DO NOT MODIFY


#
# avmm_lvds_bridge_slave "LVDS Brige Avalon-MM Slave" v1.0
#  2018.03.26.10:53:58
#
#

#
# request TCL package from ACDS 15.1
#
# package require -exact qsys 15.1
package require -exact qsys 13.1


#
# module avmm_lvds_bridge_slave
#
set_module_property DESCRIPTION ""
set_module_property NAME avmm_lvds_bridge_slave
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "LVDS Brige Avalon-MM Slave"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avmm_lvds_bridge_avs
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avmm_lvds_bridge_pkg.sv SYSTEM_VERILOG PATH avmm_lvds_bridge_pkg.sv
add_fileset_file avmm_lvds_bridge_avs.sv SYSTEM_VERILOG PATH avmm_lvds_bridge_avs.sv TOP_LEVEL_FILE
add_fileset_file avmm_lvds_bridge_avs_if.sv SYSTEM_VERILOG PATH avmm_lvds_bridge_avs_if.sv
add_fileset_file avmm_lvds_bridge_rx_fifo.sv SYSTEM_VERILOG PATH avmm_lvds_bridge_rx_fifo.sv
add_fileset_file avmm_lvds_bridge_tx_fifo.sv SYSTEM_VERILOG PATH avmm_lvds_bridge_tx_fifo.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avmm_lvds_bridge_avs
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avmm_lvds_bridge_pkg.sv SYSTEM_VERILOG PATH avmm_lvds_bridge_pkg.sv
add_fileset_file avmm_lvds_bridge_avs.sv SYSTEM_VERILOG PATH avmm_lvds_bridge_avs.sv
add_fileset_file avmm_lvds_bridge_avs_if.sv SYSTEM_VERILOG PATH avmm_lvds_bridge_avs_if.sv
add_fileset_file avmm_lvds_bridge_rx_fifo.sv SYSTEM_VERILOG PATH avmm_lvds_bridge_rx_fifo.sv
add_fileset_file avmm_lvds_bridge_tx_fifo.sv SYSTEM_VERILOG PATH avmm_lvds_bridge_tx_fifo.sv


#
# parameters
#
add_parameter REQ_FACTOR NATURAL 1 ""
set_parameter_property REQ_FACTOR DEFAULT_VALUE 1
set_parameter_property REQ_FACTOR DISPLAY_NAME REQ_FACTOR
set_parameter_property REQ_FACTOR WIDTH ""
set_parameter_property REQ_FACTOR TYPE NATURAL
set_parameter_property REQ_FACTOR UNITS None
set_parameter_property REQ_FACTOR ALLOWED_RANGES 0:2147483647
set_parameter_property REQ_FACTOR DESCRIPTION ""
set_parameter_property REQ_FACTOR HDL_PARAMETER true
add_parameter RESP_FACTOR NATURAL 1 ""
set_parameter_property RESP_FACTOR DEFAULT_VALUE 1
set_parameter_property RESP_FACTOR DISPLAY_NAME RESP_FACTOR
set_parameter_property RESP_FACTOR WIDTH ""
set_parameter_property RESP_FACTOR TYPE NATURAL
set_parameter_property RESP_FACTOR UNITS None
set_parameter_property RESP_FACTOR ALLOWED_RANGES 0:2147483647
set_parameter_property RESP_FACTOR DESCRIPTION ""
set_parameter_property RESP_FACTOR HDL_PARAMETER true
add_parameter BURSTCNT_W INTEGER 11
set_parameter_property BURSTCNT_W DEFAULT_VALUE 11
set_parameter_property BURSTCNT_W DISPLAY_NAME BURSTCNT_W
set_parameter_property BURSTCNT_W TYPE INTEGER
set_parameter_property BURSTCNT_W ENABLED false
set_parameter_property BURSTCNT_W UNITS None
set_parameter_property BURSTCNT_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BURSTCNT_W HDL_PARAMETER true
add_parameter ADDR_W INTEGER 19
set_parameter_property ADDR_W DEFAULT_VALUE 19
set_parameter_property ADDR_W DISPLAY_NAME ADDR_W
set_parameter_property ADDR_W TYPE INTEGER
set_parameter_property ADDR_W ENABLED false
set_parameter_property ADDR_W UNITS None
set_parameter_property ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_W HDL_PARAMETER true


#
# display items
#


#
# connection point clock_sink
#
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


#
# connection point reset_sink
#
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_i reset Input 1


#
# connection point req_tx
#
add_interface req_tx conduit end
set_interface_property req_tx associatedClock ""
set_interface_property req_tx associatedReset ""
set_interface_property req_tx ENABLED true
set_interface_property req_tx EXPORT_OF ""
set_interface_property req_tx PORT_NAME_MAP ""
set_interface_property req_tx CMSIS_SVD_VARIABLES ""
set_interface_property req_tx SVD_ADDRESS_GROUP ""

add_interface_port req_tx req_clk_i clk_i Input 1
add_interface_port req_tx req_data_o data_o Output 32/REQ_FACTOR
add_interface_port req_tx req_valid_o valid_o Output 1


#
# connection point resp_rx
#
add_interface resp_rx conduit end
set_interface_property resp_rx associatedClock ""
set_interface_property resp_rx associatedReset ""
set_interface_property resp_rx ENABLED true
set_interface_property resp_rx EXPORT_OF ""
set_interface_property resp_rx PORT_NAME_MAP ""
set_interface_property resp_rx CMSIS_SVD_VARIABLES ""
set_interface_property resp_rx SVD_ADDRESS_GROUP ""

add_interface_port resp_rx resp_clk_i clk_i Input 1
add_interface_port resp_rx resp_data_i data_i Input 32/RESP_FACTOR
add_interface_port resp_rx resp_valid_i valid_i Input 1


#
# connection point noburst
#
add_interface noburst avalon end
set_interface_property noburst addressUnits WORDS
set_interface_property noburst associatedClock clock_sink
set_interface_property noburst associatedReset reset_sink
set_interface_property noburst bitsPerSymbol 8
set_interface_property noburst burstOnBurstBoundariesOnly false
set_interface_property noburst burstcountUnits WORDS
set_interface_property noburst explicitAddressSpan 0
set_interface_property noburst holdTime 0
set_interface_property noburst linewrapBursts false
set_interface_property noburst maximumPendingReadTransactions 0
set_interface_property noburst maximumPendingWriteTransactions 0
set_interface_property noburst readLatency 0
set_interface_property noburst readWaitTime 1
set_interface_property noburst setupTime 0
set_interface_property noburst timingUnits Cycles
set_interface_property noburst writeWaitTime 0
set_interface_property noburst ENABLED true
set_interface_property noburst EXPORT_OF ""
set_interface_property noburst PORT_NAME_MAP ""
set_interface_property noburst CMSIS_SVD_VARIABLES ""
set_interface_property noburst SVD_ADDRESS_GROUP ""

add_interface_port noburst s0_address_i address Input ADDR_W
add_interface_port noburst s0_byteenable_i byteenable Input 4
add_interface_port noburst s0_writedata_i writedata Input 32
add_interface_port noburst s0_readdata_o readdata Output 32
add_interface_port noburst s0_write_i write Input 1
add_interface_port noburst s0_read_i read Input 1
add_interface_port noburst s0_waitrequest_o waitrequest Output 1
set_interface_assignment noburst embeddedsw.configuration.isFlash 0
set_interface_assignment noburst embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment noburst embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment noburst embeddedsw.configuration.isPrintableDevice 0


#
# connection point burst
#
add_interface burst avalon end
set_interface_property burst addressUnits WORDS
set_interface_property burst associatedClock clock_sink
set_interface_property burst associatedReset reset_sink
set_interface_property burst bitsPerSymbol 8
set_interface_property burst burstOnBurstBoundariesOnly false
set_interface_property burst burstcountUnits WORDS
set_interface_property burst explicitAddressSpan 0
set_interface_property burst holdTime 0
set_interface_property burst linewrapBursts false
set_interface_property burst maximumPendingReadTransactions 1
set_interface_property burst maximumPendingWriteTransactions 0
set_interface_property burst readLatency 0
set_interface_property burst readWaitTime 1
set_interface_property burst setupTime 0
set_interface_property burst timingUnits Cycles
set_interface_property burst writeWaitTime 0
set_interface_property burst ENABLED true
set_interface_property burst EXPORT_OF ""
set_interface_property burst PORT_NAME_MAP ""
set_interface_property burst CMSIS_SVD_VARIABLES ""
set_interface_property burst SVD_ADDRESS_GROUP ""

add_interface_port burst s1_address_i address Input ADDR_W
add_interface_port burst s1_writedata_i writedata Input 32
add_interface_port burst s1_readdata_o readdata Output 32
add_interface_port burst s1_write_i write Input 1
add_interface_port burst s1_read_i read Input 1
add_interface_port burst s1_waitrequest_o waitrequest Output 1
add_interface_port burst s1_readdatavalid_o readdatavalid Output 1
add_interface_port burst s1_burstcount_i burstcount Input BURSTCNT_W
set_interface_assignment burst embeddedsw.configuration.isFlash 0
set_interface_assignment burst embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment burst embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment burst embeddedsw.configuration.isPrintableDevice 0

